spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
management.endpoints.web.exposure.include=health,info
app.output.dir=${APP_OUTPUT_DIR:/app/outputs}
