spring.application.name=poc-backend
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/poc_vermeg
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=health,info
app.output.dir=./outputs
app.jwt.secret=VermegPOC2025SuperSecretKeyForJWTTokenGeneration256Bits
app.jwt.expiration=86400000

# Mail config (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:vermeg.poc.noreply@gmail.com}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Frontend URL pour les liens dans les emails
app.frontend.url=${FRONTEND_URL:http://localhost:3000}
